version: '2.3'
services: 
  express: 
    build: ./ 
    command: nodemon -L --inspect=0.0.0.0:5858 app.js 
    volumes: 
      - ./:/nodeapp 
      - /nodeapp/node_modules 
    ports: 
      - "3000:8080" 
      - "5858:5858"

